# ??? ?? ?? ?? (????? ??? ???? ???? ???? ????.)

  # SQL DB
spring:
  jpa:
    show-sql: true
    # ??? ?? ?? data.sql ??
    defer-datasource-initialization: true
    properties:
      # ??? ?? ?? data.sql ??
      defer-datasource-initialization: true
      hibernate:
        format_sql: true
        # ?? ???
        default_schema: test
        # Postgres
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      show_sql: true # app ????? db? ??? ??? ??? ????? ????.
      logging.level:
        org.hibernate:
          SQL: debug

    # ????: spring.jpa.hibernate.naming' to org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties$Naming:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

---
server:
  port: 28005
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://211.115.206.189:5432/davinci"
    username: "seowon"
    password: "tjdnjs1!"