# ??? ?? ?? ?? (????? ??? ???? ???? ???? ????.)

  # SQL DB
spring:
  jpa:
    show-sql: true
    # ??? ?? ?? data.sql ??
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_schema: test
        # Postgres
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: validate # 엔티티클래스와 테이블이 정상적으로 맵핑되는지만 검사한다.
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

---
server:
  port: 28005
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://211.115.206.189:5432/davinci"
    username: "seowon"
    password: "tjdnjs1!"
  sql:
    init:
      encoding: utf-8
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql